glslc main.vert -o main.vert.spv
glslc main.frag -o main.frag.spv
glslc ui.vert -o ui.vert.spv
glslc ui.frag -o ui.frag.spv
glslc debug.vert -o debug.vert.spv
glslc Sprite.frag -o Sprite.frag.spv
glslc Sprite.vert -o Sprite.vert.spv
glslc CubeMap.frag -o CubeMap.frag.spv
glslc CubeMap.vert -o CubeMap.vert.spv
glslc shadows.vert -o shadows.vert.spv